-- CreateTable
CREATE TABLE "Prueba" (
    "id" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    "sigma" REAL NOT NULL,
    "densidad" INTEGER NOT NULL DEFAULT 10,
    "createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" DATETIME NOT NULL
);
